# Jekyll Configuration

# Github Enforced
lsi: false
# safe: true

# Site settings
title: dupeGuru
description: >- 
  dupeGuru is a cross-platform (Linux, OS X, Windows) GUI tool to find duplicate files in a system. 
  It's written mostly in Python 3 and has the peculiarity of using multiple GUI toolkits, all using
   the same core Python code. On OS X, the UI layer is written in Objective-C and uses Cocoa. On 
   Linux & Windows, it's written in Python and uses Qt5.
timezone: US/Central
encoding: utf-8
url: "https://dupeguru.voltaicides.net" # the protocol and host name
baseurl: "" # the subpath 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge
gist:
  noscript: false

# links
permalink: date

# theme
theme: minima

# Plugins
plugins:
  # Default enabled
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate 
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # Optional
  - jekyll-feed
  #- jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  #- jekyll-mentions
  #- jekyll-include-cache #potentially a good idea review this

# Plugin Configurations
readme_index:
  enabled:          true
  remove_originals: true

# Defaults for the front matter
defaults:

# Excludes
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'CNAME',
  'node_modules',
  'vendor',
]

# Extra Variables for the templates
tagline: finds duplicate files
